### ISSUE TITLE
Dino walking AI causes a lot of lag, zero-gravity movement, and high GC

### ISSUE THREAD

**Issue by ciak2009** [gegy1000/JurassiCraft2#101]
At the time of this image the built-in server was at 3TPS,

It appears to be an issue with dino AI.

<img width="1238" alt="screen 20shot 202016-10-10 20at 2019 20 55" src="https://cloud.githubusercontent.com/assets/3947157/19254154/d14f0936-8f1e-11e6-94b7-c69b2414dd2b.png">

GC seems to be uncommonly high as well.
<img width="1248" alt="screen-shot-2016-10-10-at-7 39 28-pm" src="https://cloud.githubusercontent.com/assets/3947157/19254426/68996028-8f21-11e6-95f3-7b742d707275.png">

And this video shows the client in a very strange low-gravity movement type. (gif is at 30fps so I'm not sure if its clearly visible)

<img width="1238" alt="screen 20shot 202016-10-10 20at 2019 20 55" src="https://cloud.githubusercontent.com/assets/3947157/19254371/e050f83e-8f20-11e6-84fe-aa3e831b349b.gif">

If I can provide anything else just let me know.

Thanks!

**Comment by gegy1000** [comment]
Thanks for the info, I'll see what I can do to reduce it as far as possible. :)

**Comment by gegy1000** [comment]
Do you have brachiosaurus or tyrannosaurus in your world?

**Comment by gegy1000** [comment]
This is caused by large bounding boxes, causing the game to scan the nearby blocks over the whole bounding box. I'm working on making the collision box smaller to improve on this performance.

**Comment by gegy1000** [comment]
Opening this again because it's still not the greatest performance.

**Comment by gegy1000** [comment]
Improved this a lot in the latest commit - not sure how much of a problem this still is.

**Comment by gegy1000** [comment]
https://gfycat.com/DistantQuaintGuanaco
