### ISSUE TITLE
Crash when placing jeep.

### ISSUE THREAD

**Issue by Shybella** [gegy1000/JurassiCraft2#102]
Description: Ticking entity

java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Float
    at org.jurassicraft.server.entity.vehicle.CarEntity.func_70071_h_(CarEntity.java:197)
    at net.minecraft.world.World.func_72866_a(World.java:1964)
    at net.minecraft.world.World.func_72870_g(World.java:1934)
    at net.minecraft.world.World.func_72939_s(World.java:1750)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at org.jurassicraft.server.entity.vehicle.CarEntity.func_70071_h_(CarEntity.java:197)
    at net.minecraft.world.World.func_72866_a(World.java:1964)
    at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
    Entity Type: jurassicraft.jeep_wrangler (org.jurassicraft.server.entity.vehicle.JeepWranglerEntity)
    Entity ID: 3409
    Entity Name: entity.jurassicraft.jeep_wrangler.name
    Entity's Exact location: -165.50, 64.00, -49.50
    Entity's Block location: World: (-166,64,-50), Chunk: (at 10,4,14 in -11,-4; contains blocks -176,0,-64 to -161,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Entity's Momentum: 0.00, 0.00, 0.00
    Entity's Passengers: []
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1750)

**Comment by Shybella** [comment]
Although, I am having this same sorta error with Mo' Creatures and Grapple Hooks.

Mo'Creatures has tried resolving the issue in the latest update but was not resolved. I'm not sure if this helps.

Thank you!

**Comment by gegy1000** [comment]
What other mods do you have?

**Comment by Shybella** [comment]
1.10-chunkedgeindicator-1.3.jar
Bagginses-1.10.2-3.0.4e.jar
BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar
BrandonsCore-1.10.2-2.1.0.48-universal.jar
Chameleon-1.10-2.1.7.jar
ChickenChunks-1.10.2-2.1.5.40-universal.jar
Chisel-MC1.9.4-0.0.6.51.jar
CodeChickenCore-1.10.2-2.3.2.82-universal.jar
CraftTweaker-1.10.2-3.0.12.jar
CustomMainMenu-MC1.10.2-2.0.2.jar
CustomMobSpawner 3.10.0.jar
CustomNPCs_1.10.2_beta(10oct16).jar
Draconic-Evolution-1.10.2-2.0.0d.107-universal.jar
ElevatorMod[V.1.2.0][MC.1.10.2].jar
EnderCore-1.10.2-0.4.1.56-beta.jar
EnderIO-1.10.2-3.0.1.120_beta.jar
EnderStorage-1.10.2-2.1.5.80-universal.jar
ExtremeReactors-1.10.2-0.4.5.17.jar
ImmersiveEngineering-0.10-44.jar
InfernalMobs-1.10.jar
InfinityStorage-0.2.jar
InventoryTweaks-1.61-58.jar
ItemBlacklist-1.9.4-1.2.0.11.jar
JurassiCraft-2.0.4.jar
JustEnoughResources-1.10.2-0.5.2.57.jar
LaunchGui-1.9.4-2.0.3-21-client.jar
MCMultiPart-1.2.1-universal.jar
Mantle-1.10.2-1.0.0.jar
OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
Pam's HarvestCraft 1.9.4-1.10.2f.jar
ProjectE-1.10.2-PE1.0.6B.jar
Railcraft_1.10.2-10.0.0-beta-2.jar
RandomThings-MC1.10.2-3.7.6.jar
RebornCore-1.10.2-2.7.3.46-universal.jar
Reliquary-1.10.2-1.3.3.571.jar
ResourceLoader-MC1.9.4-1.5.1.jar
Slugs Converters.jar
SoulShards-TOW-1.10.2-2.6.4-44.jar
StorageDrawers-1.10.2-3.2.7.jar
TConstruct-1.10.2-2.5.5.jar
TechReborn-1.10.2-1.4.7.70-universal.jar
Waila-1.7.0-B3_1.9.4.jar
WailaHarvestability-mc1.10.2-1.1.9.jar
WorldEditCuiFe-v1.0.4-mf-1.10.2-12.18.1.2026.jar
bdlib-1.12.2.14-mc1.10.2.jar
boatifull-0.1.jar
chiselsandbits-12.5.jar
endertanks-1.10.0-1.4.2.jar
extrautils2-1.10.2-alpha-1.1.0c.jar
forestry_1.10.2-5.2.14.270.jar
generators-0.9.20.15-mc1.10.2.jar
industrialcraft-2-2.6.69-ex110.jar
infinityLib-0.1.jar
ironchest-1.10.2-7.0.11.797.jar
jefb_1.10.2-1.0.4.jar
jei_1.10.2-3.12.7.314.jar
jeibees-0.9.0.3-mc1.10.2.jar
llibrary-1.7.0-1.10.2.jar
malisiscore-1.10.2-4.2.5.jar
malisisdoors-1.10.2-5.1.3.jar
mcjtylib-1.10-2.1.4.jar
morebees-1.10.2-1.1.3.jar
multistorage-1.10.0-1.2.3b.jar
natura-1.10.2-4.0.0.85.jar
refinedstorage-1.1.3.jar
rftools-1.10-5.51.jar
shetiphiancore-1.10.0-3.3.1.jar
supercraftingframe-1.10.2-1.2.1.88.jar
worldedit-forge-mc1.10.2-6.1.4-dist.jar
zerocore-1.10.2-0.0.8.0.jar
ic2/EJML-core-0.26.jar
1.10.2/CodeChickenLib-1.10.2-2.4.1.101-universal.jar

**Comment by gegy1000** [comment]
Wow, that is a lot. Does the problem occur if you use just JurassiCraft and LLibrary?

**Comment by Shybella** [comment]
I will give that a try. It seems to only happen randomly at times. I was thinking another mod may be provoking what's going on

**Comment by gegy1000** [comment]
Did this have any effect?

**Comment by gegy1000** [comment]
Assuming this is an incompatibility.
