### ISSUE TITLE
Dinosaurs stucks in water ponds borders until starved 

### ISSUE THREAD

**Issue by jonabrv1965** [gegy1000/JurassiCraft2#103]
As I mentioned in the curse page comments I'm facing a weird situation with the dinos : they enter in the water pond and cannot exit it and die of starvation. Below you will find a pictures sequence that depict this situation. It is happening continuously and with any dino's race and age, pay attention to the hunger bar in the images and take note about the color changes between each picture. Additionally I'm attaching the latest FML log to give you detailed info about my environment (Mods, versions, etc.)

[fml-client-latest.zip](https://github.com/gegy1000/JurassiCraft2/files/532369/fml-client-latest.zip)

For me this is a break mod issue and cannot keep going with the mod until fixed (I cannot be babysitting the dinos all the time) I beg you for your support on this one. Your mode is awesome and I want to have my park.... badly :-)

![2016-10-16_21 49 47](https://cloud.githubusercontent.com/assets/13445986/19424205/f2e68470-93ec-11e6-9255-38ce27092a32.png)
![2016-10-16_21 49 48](https://cloud.githubusercontent.com/assets/13445986/19424204/f2e5aed8-93ec-11e6-8eba-ead50682e06f.png)
![2016-10-16_21 49 50](https://cloud.githubusercontent.com/assets/13445986/19424203/f2e55fbe-93ec-11e6-8e91-13269be5e0c0.png)
![2016-10-16_21 49 51](https://cloud.githubusercontent.com/assets/13445986/19424207/f2e899c2-93ec-11e6-9021-3bf728b5a57b.png)
![2016-10-16_21 49 52](https://cloud.githubusercontent.com/assets/13445986/19424206/f2e7088c-93ec-11e6-9386-12d1cdee067c.png)
![2016-10-16_21 49 55](https://cloud.githubusercontent.com/assets/13445986/19424208/f2eb3c4a-93ec-11e6-997f-7d87d1455974.png)
![2016-10-16_21 49 57](https://cloud.githubusercontent.com/assets/13445986/19424209/f2f7ab88-93ec-11e6-9b16-366f7bb4eee6.png)
![2016-10-16_21 49 58](https://cloud.githubusercontent.com/assets/13445986/19424210/f2f9c738-93ec-11e6-9f7c-f0d04b8d06dd.png)
![2016-10-16_21 55 35](https://cloud.githubusercontent.com/assets/13445986/19424211/f2fbbc5a-93ec-11e6-8a94-d46e3a02352e.png)
![2016-10-16_21 55 58](https://cloud.githubusercontent.com/assets/13445986/19424213/f2fe4a42-93ec-11e6-8189-8107a7e29206.png)
![2016-10-16_21 57 26](https://cloud.githubusercontent.com/assets/13445986/19424212/f2fc3b80-93ec-11e6-96fd-2b0396ee6c9f.png)
![2016-10-16_21 58 22](https://cloud.githubusercontent.com/assets/13445986/19424214/f2ffaac2-93ec-11e6-8421-c7215ea76416.png)
![2016-10-16_21 58 24](https://cloud.githubusercontent.com/assets/13445986/19424215/f30d27d8-93ec-11e6-97b4-fb433cdb1356.png)
![2016-10-16_21 58 26](https://cloud.githubusercontent.com/assets/13445986/19424216/f30fdd34-93ec-11e6-82df-99ee9ddc93d8.png)
![2016-10-16_21 58 26_2](https://cloud.githubusercontent.com/assets/13445986/19424218/f3115b3c-93ec-11e6-8fc8-f81277264b5d.png)
![2016-10-16_21 58 27](https://cloud.githubusercontent.com/assets/13445986/19424217/f310f9f8-93ec-11e6-8b5e-a0a5f79dcdf9.png)
![2016-10-16_21 58 28](https://cloud.githubusercontent.com/assets/13445986/19424219/f3136da0-93ec-11e6-8f46-89eaf78a80d9.png)
![2016-10-16_21 58 29](https://cloud.githubusercontent.com/assets/13445986/19424220/f316383c-93ec-11e6-8362-3855b28b0e30.png)
![2016-10-16_21 58 31](https://cloud.githubusercontent.com/assets/13445986/19424221/f32067da-93ec-11e6-8d68-7b7438fe61b8.png)
![2016-10-16_21 58 31_2](https://cloud.githubusercontent.com/assets/13445986/19424222/f3231066-93ec-11e6-847a-520cc0ab57e1.png)
![2016-10-16_21 58 32](https://cloud.githubusercontent.com/assets/13445986/19424224/f32ae142-93ec-11e6-9ebc-0091d24cd66d.png)
![2016-10-16_21 58 33](https://cloud.githubusercontent.com/assets/13445986/19424223/f32647a4-93ec-11e6-9d77-0da181930be6.png)
![2016-10-16_22 02 58](https://cloud.githubusercontent.com/assets/13445986/19424225/f32ceb0e-93ec-11e6-9764-ec7bab33832f.png)
![2016-10-16_22 03 55](https://cloud.githubusercontent.com/assets/13445986/19424226/f32e9a6c-93ec-11e6-9065-1f2fc3cfffa6.png)

**Comment by gegy1000** [comment]
This was recently fixed, but it hasn't been released yet.
