### ISSUE TITLE
Dinos seem to migrate north-west indefinitely 2.0.4

### ISSUE THREAD

**Issue by Wharv10** [gegy1000/JurassiCraft2#104]
Not sure if coincidence or not, but every dino I place (Parasaurolophus specifically) eventually ends up as far north west as it can go, and only stops when it hits a wall it can't get over. If I put more than one down, they all group together in the northwest corner and never leave.

**Comment by gegy1000** [comment]
Does this not occur in 2.0.3?

**Comment by Wharv10** [comment]
Not sure about 2.0.3 and lower. The 2.0.4 was just saying that this happens in the latest version.

**Comment by gegy1000** [comment]
Okay. Will look into it.

**Comment by Wharv10** [comment]
Didn't even know they could herd, but yeah they were all together.

**Comment by gegy1000** [comment]
If you create more herds, further away, do they also move north east?
