### ISSUE TITLE
Error in build.gradle

### ISSUE THREAD

**Issue by Tsoccerguy3** [gegy1000/JurassiCraft2#106]
Can you fix this Error while running build.gradle from command line .  This saves time pulling and compiling builds without opening a coding environment. Having the project compile from the command line allows to schedule a pull from GIT and compile , then move the *.jar to the Minecraft directory ready for testing . Simple automation  
	
It simply means that you are calling methods which have been marked with a @Deprecated annotation. If you compile with -Xlint:deprecation as a command line argument, it will tell you which ones those are
Adding these lines to build.gradle will show you what to fix

compileJava {
    options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
}

will help find any errors . Doing this will show that there are 100 warnings and 1 error in the project and what to fix

`#################################################
         ForgeGradle 2.2-SNAPSHOT-c438b06        
  https://github.com/MinecraftForge/ForgeGradle  
#################################################
               Powered by MCP unknown               
             http://modcoderpack.com             
         by: Searge, ProfMobius, Fesh0r,         
         R4wk, ZeuX, IngisKahn, bspkrs           
#################################################
:deobfCompileDummyTask
:getVersionJson
:extractUserdev
Download http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.2.2099/forge-1.10.2-12.18.2.2099.pom
Download http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.2.2099/forge-1.10.2-12.18.2.2099-userdev.jar
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:applyBinaryPatches
:deobfProvidedDummyTask
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:extractMcpMappings
Download http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp_snapshot/20161015-1.10.2/mcp_snapshot-20161015-1.10.2.zip
:genSrgs
:deobfMcMCP
Applying SpecialSource...
Applying Exceptor...
:sourceApiJava UP-TO-DATE
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:sourceMainJava
:compileJava%USER%\jc2\build\sources\main\java\org\jurassicraft\server\entity\DinosaurSerializers.java:18: error: read(PacketBuffer) in <anonymous org.jurassicraft.server.entity.DinosaurSerializers$1> cannot implement read(PacketBuffer) in DataSerializer
        public DinosaurEntity.Order read(PacketBuffer buf) throws IOException {
                                    ^
  overridden method does not throw IOException
  where T is a type-variable:
    T extends Object declared in interface DataSerializer
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 35.752 secs`

**Comment by gegy1000** [comment]
Interesting, I got this error when trying to setup with TeamCity, but don't have this otherwise.

**Comment by gegy1000** [comment]
Ah, okay. Thanks.

**Comment by iLexiconn** [comment]
You shouldn't call the deprecated `Block` methods, call the methods from the block state instead.

**Comment by gegy1000** [comment]
I am referring to the overridden methods on `Block`.

**Comment by iLexiconn** [comment]
Ah

**Comment by Tsoccerguy3** [comment]
Just checked and build.gradle is again broken

:deobfCompileDummyTask
:getVersionJson
:extractUserdev UP-TO-DATE
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:applyBinaryPatches SKIPPED
:deobfProvidedDummyTask
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:deobfMcMCP SKIPPED
:sourceApiJava UP-TO-DATE
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:sourceMainJava UP-TO-DATE
:compileJava
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not resolve net.ilexiconn:llibrary:1.7.0-1.10.2.
  Required by:
      project :
   > Could not resolve net.ilexiconn:llibrary:1.7.0-1.10.2.
      > Could not get resource 'https://libraries.minecraft.net/net/ilexiconn/llibrary/1.7.0-1.10.2/llibrary-1.7.0-1.10.2.pom'.
         > Could not HEAD 'https://libraries.minecraft.net/net/ilexiconn/llibrary/1.7.0-1.10.2/llibrary-1.7.0-1.10.2.pom'. Received status code 403 from server: Forbidden
   > Could not resolve net.ilexiconn:llibrary:1.7.0-1.10.2.
      > Could not get resource 'http://maven.mdmocdev.com/net/ilexiconn/llibrary/1.7.0-1.10.2/llibrary-1.7.0-1.10.2.pom'.
         > Could not HEAD 'http://maven.mdmocdev.com/net/ilexiconn/llibrary/1.7.0-1.10.2/llibrary-1.7.0-1.10.2.pom'.
            > maven.mdmocdev.com

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


BUILD FAILED

Total time: 6.219 secs

**Comment by gegy1000** [comment]
Update Java to the latest version

**Comment by Tsoccerguy3** [comment]
Thanks gegy , just noticed this early today .

Running Java 8 x64 build 112

I Fixed by replacing lex's Repo in build.gradle from

		name = "ilexiconn"
		url = "http://maven.mdmocdev.com"
to
                name = "ilexiconn"
                url = "http://maven.ilexiconn.net"
