### ISSUE TITLE
Dilophosaurus spawning

### ISSUE THREAD

**Issue by MeinKraft** [gegy1000/JurassiCraft2#107]
Forge: 2120
MC: 1.10.2
JurassiCraft2: 2.04.

Dilophosaurus' spawn even when "Dinosaur Spawning"=false is set in the config

**Comment by gegy1000** [comment]
What other mods do you have installed?

**Comment by MeinKraft** [comment]
AppleSkin
Baubles
BetterAchievements
BetterFoliage
BetterFps
BetterThanBunnies
Biomes O'Plenty
BloodMagic
Botania
Chisel
Chisel and Bits
CookingForBlockHeads
CounterGuns
Cyclic
DrZharks Mo Creatures / Mob Spawners
EnderIO
EnderZoo
ExtraUtils
Forestry
Gravestone
ImmersiveEngineering
IndustrialCraft
JEI
JustEnoughResources
JourneyMap
JurassiCraft
MalassisDoors
Mekanism / Tools / Generators
MinecraftComesAlive
Mo Bends
MoreBees
MysticalAgriculture
Neat
NotEnoughWands
Optifine
PamsHarvestCraft
ProgressiveAutomation
ProjectE
RefinedStorage
RFTools
StorageDrawers
TConstruct
Terraqueous
TheOneProbe
VillageBox
XPCollector

Pretty much all latest versions for Minecraft 1.10.

**Comment by gegy1000** [comment]
Likely one of the other mods you have installed is causing them to spawn.

**Comment by MeinKraft** [comment]
After some trial and error removing mods, creating new worlds, it seems Mo Creatures mod may be responsible. Maybe 2 mobs share the same id or something.

**Comment by gegy1000** [comment]
Forge handles giving entities unique IDs. This may happen if there are too many entities in your installation.
