### ISSUE TITLE
duplication bug with the Jeep Wrangler

### ISSUE THREAD

**Issue by TheDCPlaya** [gegy1000/JurassiCraft2#108]
when you drive into Vanilla Cactus it causes the Jeep to break and give you more than 1 back.
he is a gif i made of the issue https://www.dropbox.com/s/eggdkw8r551x92e/2016-11-15_20-33-32.gif?dl=0

**Comment by gegy1000** [comment]
Interesting, thanks for the report. I cannot seem to reproduce this.
