### ISSUE TITLE
Dinosaur cause ticking world

### ISSUE THREAD

**Issue by MachinegunMarty** [gegy1000/JurassiCraft2#109]
Hey Gegy1000,

I made some Gallimimus (3x) and placed them in the world.

My server console keeps spamming "Did the server time change ? walking behind 1000 Ticks...." every 15 sec. 

Pick up the dino (with a enderio: soul vial) my world ticking stops.

Games gets real slow to a point of disconnects and then crashes (clients and server)

Saw that a closed issue was the same, but in the 2.0.4 version still have this problem.

I am using 171 Mods so couldn't give you an answer if it is 2 mod interfering. (I'm not using Mo' Creatures)

Hope it gets fixed in a later version.

**Comment by gegy1000** [comment]
This was fixed after 2.0.4 was released.

**Comment by MachinegunMarty** [comment]
Ok,

Any ETA on when you are  gonna release an update ?
