### ISSUE TITLE
Tamable Mobs don't Defend you

### ISSUE THREAD

**Issue by TheLastBlockbender** [gegy1000/JurassiCraft2#110]
I know that some mobs are tamable such as the Raptor or the Triceratops, but whenever I get attacked or I attack something, they don't do anything.

**Comment by gegy1000** [comment]
But are those mobs tamed to you?

**Comment by gegy1000** [comment]
Also make sure they are an adult, they don't defend you until then.

**Comment by gegy1000** [comment]
Okay, this is definitely a problem.
