### ISSUE TITLE
Dinosaurs don't "swim" anymore.

### ISSUE THREAD

**Issue by crakiMDH** [gegy1000/JurassiCraft2#113]
OK, so I'm playing 2.0.5, and I noticed something. Dinosaurs have that same old boring "bobbing" in the water when they enter the water... So far I've seen this happening with Brachiosaurus, Gallimimus, and Triceratops. They no longer go down to the bottom of the water if its shallow enough... Nope! They just go in the water and just bob in there. It's really annoying to see that happening. Please fix this, I miss my realistic swimming dinosaurs.

Thanks.

**Comment by gegy1000** [comment]
They do this when they are not moving. This is something we had to do to get around the dinosaurs getting stuck in water.

**Comment by crakiMDH** [comment]
Oh OK... So does that mean that dinosaurs can't walk in the bottom of the water anymore?
OK...

**Comment by gegy1000** [comment]
They will, because if they are walking, they are moving.
