### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by Emortalnight** [gegy1000/JurassiCraft2#115]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-1.7.2-1.10.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 12/19/16 8:15 PM
Description: Ticking entity

java.lang.ClassCastException: org.jurassicraft.server.entity.DinosaurEntity$Order cannot be cast to java.lang.Integer
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:736)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.jurassicraft.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:736)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: jurassicraft.triceratops (org.jurassicraft.server.entity.dinosaur.TriceratopsEntity)
	Entity ID: 186
	Entity Name: Triceratops
	Entity's Exact location: 77.75, 62.00, -110.50
	Entity's Block location: World: (77,62,-111), Chunk: (at 13,3,1 in 4,-7; contains blocks 64,0,-112 to 79,255,-97), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.02, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['Emortal_Night'/24122, l='MpServer', x=8.50, y=65.00, z=8.50], EntityOtherPlayerMP['Armykid2009'/265, l='MpServer', x=-2.70, y=73.00, z=49.70]]
	Chunk stats: MultiplayerChunkCache: 182, 182
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,80,0), Chunk: (at 0,5,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: spectator (ID 3). Hardcore: false. Cheats: false
	Forced entities: 56 total; [EntityPlayerSP['Emortal_Night'/24122, l='MpServer', x=8.50, y=65.00, z=8.50], MoCEntitySnail['Snail'/132, l='MpServer', x=-16.23, y=71.00, z=35.59], EntityCreeper['Creeper'/23684, l='MpServer', x=39.50, y=65.00, z=-44.50], MoCEntityLion['Lion'/133, l='MpServer', x=-7.92, y=71.00, z=120.00], MoCEntityLion['Lion'/134, l='MpServer', x=12.88, y=70.00, z=109.12], EntityZombie['Zombie'/23174, l='MpServer', x=50.38, y=62.34, z=27.79], EntityZombie['Zombie'/23175, l='MpServer', x=49.38, y=62.06, z=27.27], EntityOtherPlayerMP['Armykid2009'/265, l='MpServer', x=-2.70, y=73.00, z=49.70], MoCEntityLion['Lion'/136, l='MpServer', x=1.90, y=68.00, z=-118.47], EntityOtherPlayerMP['Armykid2009'/265, l='MpServer', x=-2.70, y=73.00, z=49.70], MoCEntityFly['Fly'/138, l='MpServer', x=4.44, y=63.00, z=-72.79], MoCEntityScorpion['Scorpion'/23946, l='MpServer', x=93.50, y=67.00, z=-4.50], EntitySkeleton['Skeleton'/23820, l='MpServer', x=55.50, y=63.00, z=-32.50], MoCEntityLion['Lion'/143, l='MpServer', x=9.95, y=70.00, z=109.02], MoCEntityMole['Mole'/146, l='MpServer', x=22.69, y=65.00, z=-119.27], MoCEntityWraith['Wraith'/24082, l='MpServer', x=66.50, y=76.74, z=117.50], EntitySkeleton['Skeleton'/23571, l='MpServer', x=37.51, y=66.00, z=6.78], EntitySkeleton['Skeleton'/23572, l='MpServer', x=51.27, y=67.00, z=14.51], MoCEntityLion['Lion'/149, l='MpServer', x=21.00, y=66.00, z=-94.06], EntitySkeleton['Skeleton'/23573, l='MpServer', x=29.48, y=68.00, z=10.70], EntitySkeleton['Skeleton'/23957, l='MpServer', x=71.50, y=65.00, z=22.50], MoCEntityDeer['Deer'/150, l='MpServer', x=42.77, y=62.64, z=42.40], MoCEntityDeer['Deer'/151, l='MpServer', x=40.58, y=62.65, z=27.62], MoCEntityEnt['Ent'/152, l='MpServer', x=-25.96, y=69.00, z=23.00], MoCEntityEnt['Ent'/153, l='MpServer', x=43.73, y=62.65, z=66.27], MoCEntityLion['Lion'/154, l='MpServer', x=29.00, y=67.00, z=77.04], MoCEntityGreenOgre['GreenOgre'/22300, l='MpServer', x=7.11, y=74.00, z=16.61], EntityZombie['Zombie'/24093, l='MpServer', x=71.50, y=65.00, z=22.50], EntitySkeleton['Skeleton'/23453, l='MpServer', x=80.48, y=68.00, z=44.77], MoCEntityLion['Lion'/20640, l='MpServer', x=46.99, y=70.00, z=127.08], EntityZombie['Zombie'/23585, l='MpServer', x=57.50, y=66.00, z=-17.50], MoCEntityLion['Lion'/166, l='MpServer', x=39.09, y=68.00, z=76.99], MoCEntityLion['Lion'/167, l='MpServer', x=30.11, y=71.00, z=97.89], EntityZombie['Zombie'/24109, l='MpServer', x=31.50, y=67.00, z=77.50], EntitySkeleton['Skeleton'/23981, l='MpServer', x=84.23, y=67.00, z=-0.53], MoCEntityAnt['Ant'/174, l='MpServer', x=63.06, y=70.00, z=-68.49], MoCEntityMaggot['Maggot'/175, l='MpServer', x=56.75, y=66.00, z=26.50], EntityZombie['Zombie'/23090, l='MpServer', x=51.54, y=67.00, z=22.41], EntityZombie['Zombie'/23091, l='MpServer', x=49.97, y=62.35, z=29.03], MoCEntityScorpion['Scorpion'/23092, l='MpServer', x=56.16, y=64.00, z=-5.06], EntitySpider['Spider'/23222, l='MpServer', x=58.70, y=63.10, z=55.30], EntitySkeleton['Skeleton'/24118, l='MpServer', x=93.50, y=63.00, z=-22.50], DinosaurEntity{ Triceratops, id=186, remote=true, isDead=false, isCarcass=false, isSleeping=false, stayAwakeTime=0
    , dinosaurAge=139743, prevAge=0, maxAge135000, ticksExisted=1, entityAge=0, isMale=true, growthSpeedOffset=0
    , food=168000 / 168000 (147000.0), water=168000 / 168000 (147000.0), digestingFood=0 / 3000, health=45.152 / 70.0
    , pos=BlockPos{x=77, y=62, z=-111}, eyePos=(80.14664610721817, 64.13463878804734, -110.6194183991873), eyeHeight=1.8, lookX=0.0, lookY=0.0, lookZ=0.0
    , width=2.5, bb=box[77.57500000298023, 62.0, -110.67810387539946 -> 80.07500000298023, 65.0, -108.17810387539946] }, EntityZombie['Zombie'/23611, l='MpServer', x=75.50, y=23.00, z=-36.50], MoCEntityDeer['Deer'/192, l='MpServer', x=76.55, y=64.00, z=62.45], EntitySkeleton['Skeleton'/23236, l='MpServer', x=48.06, y=64.00, z=18.08], EntitySkeleton['Skeleton'/24007, l='MpServer', x=20.50, y=68.00, z=79.50], EntitySkeleton['Skeleton'/23911, l='MpServer', x=66.50, y=63.00, z=64.50], EntityZombie['Zombie'/24042, l='MpServer', x=38.50, y=70.00, z=-66.50], MoCEntityFlameWraith['FlameWraith'/23915, l='MpServer', x=61.25, y=69.68, z=-19.18], MoCEntityMaggot['Maggot'/110, l='MpServer', x=-21.47, y=70.00, z=-89.06], MoCEntityBee['Bee'/111, l='MpServer', x=-8.50, y=68.00, z=-38.10], MoCEntityMaggot['Maggot'/112, l='MpServer', x=-20.38, y=68.00, z=-53.54], EntitySquid['Squid'/23537, l='MpServer', x=58.60, y=61.00, z=52.60], EntitySquid['Squid'/22775, l='MpServer', x=46.60, y=62.48, z=22.40], MoCEntitySnail['Snail'/126, l='MpServer', x=-22.92, y=69.00, z=32.61]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2316354752 bytes (2209 MB) / 3070754816 bytes (2928 MB) up to 6681526272 bytes (6372 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7168M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJA	BiomesOPlenty{5.0.0.2109} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar) 
	UCHIJA	mocreatures{10.0.6} [DrZhark's Mo'Creatures Mod] (DrZhark's Mo'Creatures Mod-10.0.6.jar) 
	UCHIJA	JEI{3.13.6.392} [Just Enough Items] (jei_1.10.2-3.13.6.392.jar) 
	UCHIJA	journeymap{1.10.2-5.3.2} [JourneyMap] (journeymap-1.10.2-5.3.2.jar) 
	UCHIJA	llibrary{1.7.2} [LLibrary] (llibrary-1.7.2-1.10.2.jar) 
	UCHIJA	jurassicraft{2.0.5} [JurassiCraft] (JurassiCraft-2.0.5.jar) 
	UCHIJA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	UCHIJA	WorldEditCuiFe{1.0.2} [WorldEdit CUI Forge Edition] (WorldEditCuiFe-v1.0.4-mf-1.10.2-12.18.2.2125.jar) 
	Loaded coremods (and transformers): 
llibrary (llibrary-1.7.2-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.19' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.19, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz

**Comment by gegy1000** [comment]
Does this happen when you have no other mods installed other than JurassiCraft and LLibrary?

**Comment by GarchompGirl** [comment]
same for me when i use a breeding wand on a male dinosaur it kicks me out of my server then crashes
