### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by milo234** [gegy1000/JurassiCraft2#128]
I downloaded everything ran mc and nothings there

**Comment by gegy1000** [comment]
Could you please provide more information?

**Comment by milo234** [comment]
I've downloaded the forge it said to I have Java
I installed the Llibrary The mod the zip and when I Opened Minecraft and ran it, it didn't have the mod option 




and I have Java 8 I have it set on 1.10.2 like it said for 2.0

**Comment by gegy1000** [comment]
Are you running the forge profile?

**Comment by milo234** [comment]
and I also forgot to mention I did install the forge but do you mean like a mc forge profile because I saw that but I wasn't quite sure what it was so I left it alone

**Comment by milo234** [comment]
Thanks so much just played around with the forge profile and its working

**Comment by milo234** [comment]
wait nvm it has the forge and stuff but it doesn't have the Dinosaur mods
