### ISSUE TITLE
The Mods arnt on the modlist

### ISSUE THREAD

**Issue by milo234** [gegy1000/JurassiCraft2#129]
The forge is in the mods and some murcius mod thing and a coder pack mod but not the other mods

**Comment by gegy1000** [comment]
Did you put JurassiCraft and LLibrary in the mods folder?

**Comment by milo234** [comment]
Oh no I didn't Sorry xD I am New to Downloading mods ect  xD Thanks :P

**Comment by gegy1000** [comment]
Reopen if you have any more issues.

**Comment by milo234** [comment]
actually I do I Don't know how to access it

**Comment by gegy1000** [comment]
Here's a post I made a while back on installing mods: http://i.imgur.com/L7H0IoU.png
