### ISSUE TITLE
Sorry (Dont know how to access the mod folder)

### ISSUE THREAD

**Issue by milo234** [gegy1000/JurassiCraft2#131]
I don't know (I tried to reopen the issue I couldn't sorry)

**Comment by gegy1000** [comment]
Oh, right. I posted a solution on the old issue.

**Comment by milo234** [comment]
okay I got everything done and now it says error Llibrary wants Minecraft 1.11,1.11 I don't know` If it refers to mc 1.11 should I download the forge for that version




or that 





f

f

**Comment by milo234** [comment]
keyboard is  a bit
 broke btw`




ebsite
enc

**Comment by gegy1000** [comment]
No, you should download the right version of LLibrary that is for 1.10.2.

**Comment by milo234** [comment]
oh xD must e the w`rong version sorry
t
t
