### ISSUE TITLE
will not work on minecraft 1.7.10 with forge 1.4.0

### ISSUE THREAD

**Issue by deathray07** [gegy1000/JurassiCraft2#134]
i tried all of the forge versions and i get this error message down bellow
![minecraft 1 7 10 2_20_2017 8_55_08 pm](https://cloud.githubusercontent.com/assets/25915706/23147738/2bb525ce-f7af-11e6-86bc-6624e37f6a31.png)

llibary : minimum version required is 0.2.0-1.7.10

**Comment by pau101** [comment]
Did you install LLibrary 0.2.0-1.7.10?

**Comment by deathray07** [comment]
no can you show me a set of instructions or a link? to show me how to do so?

**Comment by pau101** [comment]
Put [LLibrary](https://minecraft.curseforge.com/projects/llibrary-legacy/files/2241234) in the mods folder along with JurassiCraft.

**Comment by deathray07** [comment]
uh this happened
![minecraft launcher 2_23_2017 10_46_36 pm](https://cloud.githubusercontent.com/assets/25915706/23289776/1d8f711c-fa1a-11e6-95fb-b9adc98a1c57.png)

**Comment by deathray07** [comment]
here is the rest
![minecraft launcher 2_23_2017 10_49_30 pm](https://cloud.githubusercontent.com/assets/25915706/23289836/6be80752-fa1a-11e6-9fed-eb839a4e675f.png)

**Comment by gegy1000** [comment]
Could you press 'Copy to clipboard' and paste that full log into a service such as [Pastebin](http://pastebin.com/)?

**Comment by deathray07** [comment]
?
i don understand?
