### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by Supernova458** [gegy1000/JurassiCraft2#135]
![screen shot 2017-02-24 at 10 40 30 pm](https://cloud.githubusercontent.com/assets/26018798/23328271/ed1c445a-fae2-11e6-8faf-be688e376947.png)
This pops up when I try opening it.. I tried it on both 1.10.2 and 1.11

**Comment by gegy1000** [comment]
You need to install a version of LLibrary for 1.10.2.

**Comment by Supernova458** [comment]
Is there a link to it?

**Comment by Cazsius** [comment]
https://minecraft.curseforge.com/projects/llibrary/files
