### ISSUE TITLE
Dinosaurs spin uncontrollably 

### ISSUE THREAD

**Issue by Wharv10** [gegy1000/JurassiCraft2#65]
![spin glitch](https://cloud.githubusercontent.com/assets/20597562/17058483/963ec402-5018-11e6-86e6-93efcae8d697.gif)

**Comment by Wharv10** [comment]
The problem I showed in this GIF is mostly fixed in 2.0.3. The mobs cant see through walls anymore, so they don't glitch out when they try and attack something they can see but not reach. The only time this is still a problem is when something large (like the T.rex) attempts to attack something in trees. If large mobs could pass through leaf/log blocks, that would fix this spinning problem 99% of the time.

**Comment by PCAwesomeness** [comment]
@Wharv10 I don't think they should be able to pass through wood.

Leaves, on the other hand...

**Comment by gegy1000** [comment]
This is caused when a mob has a hitbox with a width bigger than 1 block, it expects to fall over an edge but doesn't.
