### ISSUE TITLE
Visual glitches on models (z-fighting)

### ISSUE THREAD

**Issue by Wharv10** [gegy1000/JurassiCraft2#67]
Most common in the neck/head area. Probably (?) not fixable without editing the model.
![visual glitch](https://cloud.githubusercontent.com/assets/20597562/17058514/b7774784-5018-11e6-90e3-f2ac30b65f21.gif)

**Comment by Alex-the-666** [comment]
Thats intended

**Comment by Wharv10** [comment]
Why?

**Comment by gegy1000** [comment]
Oops, closed the wrong issue.

**Comment by gegy1000** [comment]
http://i.imgur.com/MJR08gA.png - it's fixed anyway now :P
