### ISSUE TITLE
Dinosaurs can glitch through one block thick walls

### ISSUE THREAD

**Issue by Wharv10** [gegy1000/JurassiCraft2#69]
Not sure about two or more blocks (I've seen Triceratops and Parasaurolophus do it through one).

**Comment by gegy1000** [comment]
Hmm, I can't seem to reproduce this.

**Comment by Wharv10** [comment]
I made a walled of area 5 blocks high with dinos in it, and when I came back later some were outside. I think it has something to do with the map loading them in the wrong place when you reload the chunk.

**Comment by gegy1000** [comment]
Yeah, it looks like it's caused when a chunk is reloaded.
