### ISSUE TITLE
Dinosaurs should not be able to see and attack through walls.

### ISSUE THREAD

**Issue by PCAwesomeness** [gegy1000/JurassiCraft2#84]
I know this isn't a bug, but it's super annoying. The Velociraptor enclosure is close to the Dilophosaurus one; every time the damned dromaeosaurs get too close to their neighbor enclosure, they always try to kill the dilophosaur, and due to the fact that their attacks can pass through walls, they end up killing it. In fact, I had to reduce my Velociraptor count to two individuals just so this wouldn't happen so frequently.

Also, there's a little bar between the Velociraptor enclosure and The Big One's paddock, and since I put a butcher in there, the dromies are attracted to it, even though there are SOLID WALLS and OPEN SPACE separating them.

Can this please be fixed?

**Comment by crakiMDH** [comment]
Hmm... Until the mod's code fixes it, a possible solution would be to get one of the two dinos, and move them somewhere else. It isn't so hard, since they should have been tamed.
