### ISSUE TITLE
Feeders arent working

### ISSUE THREAD

**Issue by jochuan** [gegy1000/JurassiCraft2#86]
i made a enclosure for my 2 dilophosaurus and i put  2 feeders on the sideways of a tree but the dilophosaurus starved to death and i made two water pools in the enclosure i am using 1.9.4 with the 2.0.2 version
![2016-08-07_18 53 23](https://cloud.githubusercontent.com/assets/11268912/17465560/b8f98184-5cd0-11e6-9c36-c470a5023ba0.png)
![2016-08-07_18 52 28](https://cloud.githubusercontent.com/assets/11268912/17465568/bec3575c-5cd0-11e6-95a2-29fe601c7fc6.png)
![2016-08-07_18 53 16](https://cloud.githubusercontent.com/assets/11268912/17465569/c450b700-5cd0-11e6-9fcd-db8702a8cb06.png)

**Comment by gegy1000** [comment]
Are you sure they starved?

**Comment by jochuan** [comment]
yes everyday i was going to the enclosure to see how they have growth and i noticed that the hunger bar wasnt full even with food inside the feeders and one day i didnt went to the enclosure to give food to them and in the other day i only saw a bunch of dilophosaurus bones on the ground

**Comment by jochuan** [comment]
when this will be fixed ?

**Comment by gegy1000** [comment]
I can't reproduce this, so I can't fix it yet.

**Comment by iLexiconn** [comment]
Can you send us the world

**Comment by jochuan** [comment]
i did not tested with the new forge version on that world i have pokecube, roots and weapon case loot and some others mod that dont add items or blocks installed
http://www.mediafire.com/download/qskplsg41tehs3c/Novo_Mundo_-_C%C3%B3pia.rar

**Comment by jochuan** [comment]
it still happens with the latest forge maybe it is because the feeder isn't working on different layers ?

**Comment by gegy1000** [comment]
Could you provide the coordinates of your pen?

**Comment by gegy1000** [comment]
Nevermind, I found it. The dilophosaurus eat from the feeder for me.

**Comment by jochuan** [comment]
so why it isnt working for me ?

**Comment by gegy1000** [comment]
I don't know.

**Comment by jochuan** [comment]
maybe a incompatibility with other mod when i have time i will make a list of the mods that i use and see if there is some error on the log

**Comment by jochuan** [comment]
after updating pokecube today this bug dissapeared

**Comment by gegy1000** [comment]
:)

**Comment by gegy1000** [comment]
Going to reopen this because it seems people are still having this problem.
