### ISSUE TITLE
Dilophosaurus are sleeping and lifting up

### ISSUE THREAD

**Issue by jochuan** [gegy1000/JurassiCraft2#87]
if you sleep while the dilophosaurus are awaken in the other day they will try to sleep but will be lifting up and sitting endlessly
![2016-08-07_18 33 54](https://cloud.githubusercontent.com/assets/11268912/17465588/90b2487c-5cd1-11e6-9ebb-933ccd47d6c5.png)
![2016-08-07_18 33 55](https://cloud.githubusercontent.com/assets/11268912/17465590/92853826-5cd1-11e6-9b00-12363b0e47e9.png)
![2016-08-07_18 34 00](https://cloud.githubusercontent.com/assets/11268912/17465591/94d3de70-5cd1-11e6-8c42-37bcb0876efa.png)
![2016-08-07_18 33 52](https://cloud.githubusercontent.com/assets/11268912/17465592/98baf0be-5cd1-11e6-90ac-f077a32f5427.png)

**Comment by gegy1000** [comment]
I can't seem to reproduce this

**Comment by jochuan** [comment]
i sleep while they are awaken and in the other day they have this bug

**Comment by gegy1000** [comment]
Yep, that's what I tried. It didn't happen.

**Comment by jochuan** [comment]
i sleep on the very beggining of the night where you can still see the sun i also using pokecube,roots,optifine,betterfps,Jei,liteloader,ruins,weaponcaseloot,mo'villages,baubles and chunk edge indicator.Can you test with the same world that i sent from the other issue ?

**Comment by gegy1000** [comment]
I have tested on that same world.

**Comment by jochuan** [comment]
strange i will test without pokecube to see if it happens

**Comment by jochuan** [comment]
it isn't happening anymore on 1.10.2 looks like it was a bug from 1.9.4 only
