### ISSUE TITLE
Can't put water bucket in cleaning station on server

### ISSUE THREAD

**Issue by Terpo** [gegy1000/JurassiCraft2#88]
I'm trying to use the cleaning station on our server. After putting in a water bucket it does not used up. It simply sits in the buttom slot. The cleaning station ist working in SP for me.

Modlist: http://blog.terpo.org/upload/mc/modlist.txt
Minecraft: 1.10.2
Forge: 1.10.2 - 12.18.1.2011

JurassiCraft-2.0.2.jar

**Comment by Terpo** [comment]
Thats quite interesting. After our todays server restart its working oO

**Comment by gegy1000** [comment]
Hmm, strange. Glad it's fixed though!
