### ISSUE TITLE
Dinosaurs spawn in Nether

### ISSUE THREAD

**Issue by DamnedSimoniZ** [gegy1000/JurassiCraft2#89]
Hi,
      My server always crash since I entered the nether. I had the dino spawning to true and since I turned it to false, but not I seems to have server crash in nether and overwold.

Here is one of the crash report I have, saying problem with entity.

[crash-2016-08-24_22.38.04-server.txt](https://github.com/gegy1000/JurassiCraft2/files/436080/crash-2016-08-24_22.38.04-server.txt)
I got that crash log too, but I don't know if it's related.

[crash-2016-08-24_22.32.40-server.txt](https://github.com/gegy1000/JurassiCraft2/files/436081/crash-2016-08-24_22.32.40-server.txt)

**Comment by gegy1000** [comment]
This is the strangest crash log I have ever seen. This is either caused by another mod you have installed, or caused by a corrupt jar file. I can't think of anything else.

**Comment by DamnedSimoniZ** [comment]
I managed to destroy my nether gate and close my server, then I have deleted the nether dim in my world. I walked around into my new nether and overworld all seems to works fine now. I still let dinosaur spawn to false. But i would like to get dinosaur in my overworld (was working fine before entering the nether). Is there a way to only spawn dinosaur in the overworld?

**Comment by gegy1000** [comment]
It is a bug that they are spawning in the nether.

**Comment by DamnedSimoniZ** [comment]
Thank you sir. Keep the good job. Minecraft with dinosaur = EPIC

:)

**Comment by gegy1000** [comment]
Looks like this is an incompatibility with another mod, I can't reproduce this.

**Comment by DamnedSimoniZ** [comment]
Hi, 
      With all the mods I have it would be hard to find which one the problem. For now it is working without dinosaur spawning in the world... But I must admit being chased by a T-Rex with the sound.... It's sad that I can't keep them on.

**Comment by gegy1000** [comment]
I notice you are using LLibrary, Bloodmoon-MC and AromaCore for 1.9.4 in 1.10.2, this might be a part of your problem.

**Comment by DamnedSimoniZ** [comment]
Hi,
     I have updated the mods you listed and it seems to work fine for now. I put the dino spawning to on, and they are still spawning in the nether. But the dinos spawning are better. Before they were spawning like crazy and now it seems to be ok (I kept the same config as before). I was able to walk in the nether and no server crash.

There still a bug if you say that they should not spawn in the nether.
But I can play with dinos hunting me!

Thank you for your help, and I have put the latest log in case you wanted to check why dino still spawn in the nether (I don't have a crash report, since the server didn't crashed). If you want another logs just tell me if it could help you I will put it here.

[fml-server-latest.zip](https://github.com/gegy1000/JurassiCraft2/files/441535/fml-server-latest.zip)
