### ISSUE TITLE
Dilophosaurus are entering in blocks and don't get out of the pond

### ISSUE THREAD

**Issue by jochuan** [gegy1000/JurassiCraft2#92]
i have a pen with two ponds and sometimes the dilophosaurs enter in the pond but arent able to get out of it this happens most often when you sleep while they are swimming and in the other day they are with the sleepy stats trying to get out of the pond without sucess this bug didnt happened before so it must be something with the size of them they are with 10-11 days of life a temporary fix is too select the sit button when they are stuck trying to exit the pool.
![2016-09-04_13 22 15](https://cloud.githubusercontent.com/assets/11268912/18232815/3f4865dc-72ae-11e6-89ea-d66d8c547e06.png)
![2016-09-04_13 45 07](https://cloud.githubusercontent.com/assets/11268912/18232819/4aea5f6c-72ae-11e6-85c3-e2441828e81c.png)
![2016-09-04_13 39 53](https://cloud.githubusercontent.com/assets/11268912/18232823/57f45ca8-72ae-11e6-8dd6-dd937507820f.png)

**Comment by gegy1000** [comment]
This should already be fixed for 2.0.3
