### ISSUE TITLE
Strange feeder behavior

### ISSUE THREAD

**Issue by jochuan** [gegy1000/JurassiCraft2#94]
when i am far away from the feeder it turns aside instead of being in the normal position i am using the 1.10.2 version
![2016-09-04_13 45 23](https://cloud.githubusercontent.com/assets/11268912/18421024/ffd1af3c-7855-11e6-8a5a-60057ace9257.png)
![2016-09-10_17 58 57](https://cloud.githubusercontent.com/assets/11268912/18421025/01f5b236-7856-11e6-992e-6d4a817b7ef2.png)
![2016-09-11_19 13 13](https://cloud.githubusercontent.com/assets/11268912/18421026/03f8aad4-7856-11e6-8a6a-32702ad8357a.png)

**Comment by gegy1000** [comment]
I can't reproduce this

**Comment by jochuan** [comment]
i cant make tests on my world to try to reproduce it now but this bug appeared when i updated my world from 1.9.4 to 1.10.2
