### ISSUE TITLE
Texture glitches on lab equipment

### ISSUE THREAD

**Issue by Wharv10** [gegy1000/JurassiCraft2#99]

**Comment by gegy1000** [comment]
Could you please provide more information? What do you mean by this?

**Comment by Wharv10** [comment]
Things like this needle(?). It's the same sort of glitch on the dinosaurs.

![picture1](https://cloud.githubusercontent.com/assets/20597562/19196912/418b52d0-8caf-11e6-90fd-3bd9b5aa51e4.png)
